### ISSUE TITLE
Remove willRelocateInt field from JobOrder entity

### ISSUE THREAD

**Issue by johnsully83** [bullhorn/sdk-rest#127]
Must have been legacy something or other, doesn't seem to be doing anything now, and if you request the field in a fields parameter, this is returned

{
  "errorMessage": "Invalid field 'willRelocateInt' at position 14."
}

**Comment by rmcdole** [comment]
Code supporting willRelocateInt is not ASL yet, will be by the end of the month. It was implemented to get the actual value of the field as willRelocate is actually an integer with certain field map settings, but a new field was created to represent the integer value in order to avoid breaking backwards compatibility .
