### ISSUE TITLE
Cannot able to update a candidate

### ISSUE THREAD

**Issue by manrick653** [bullhorn/sdk-rest#141]
[FATAL]: local_project.sdkrouting_0_1.sdkrouting - tJavaRow_1 {
  "errorCode" : 500,
  "errors" : [ {
    "detailMessage" : "missing required property: userType",
    "propertyName" : "userType",
    "severity" : "ERROR",
    "type" : "MISSING_REQUIRED_PROPERTY"
  } ],
  "entityName" : "Candidate",
  "errorMessage" : "error persisting an entity of type: Candidate"
}
com.bullhornsdk.data.exception.RestApiException: {
  "errorCode" : 500,
  "errors" : [ {
    "detailMessage" : "missing required property: userType",
    "propertyName" : "userType",
    "severity" : "ERROR",
    "type" : "MISSING_REQUIRED_PROPERTY"
  } ],
  "entityName" : "Candidate",
  "errorMessage" : "error persisting an entity of type: Candidate"
}

UserType class does not have the parameter based constructor.
Please help

**Comment by johnsully83** [comment]
Hello,

This error has to do with using a Candidate object that we requested from the SDK.  I.e., I'm guessing you code looks (at a very high-level) like this:

Candidate aCandidate = bullhornData.findEntity(Candidate.class, myCandidateId);
aCandidate.setCustomText1('Some value');
bullhornData.updateEntity(aCandidate);

What we want to do instead is create a new instance of the Candidate for persisting via the APIs.  This ensures we're only sending the fields we want to update to the REST APIs:

Candidate myCandidate = new Candidate(myCandidateId); //this sets the id field on the candidate
myCandidate.setCustomText1('Some value');
bullhornData.updateEntity(aCandidate);

This is a best practice, mainly because it removes any ambiguity around what you're updating.  Basically we only want to populate fields on the object we're sending to the APIs that we actually want to change.

**Comment by manrick653** [comment]
thanks for the suggestion @johnsully83
