### ISSUE TITLE
Request for new field (relating to support ticket 03817692)

### ISSUE THREAD

**Issue by joncampbelldev** [bullhorn/sdk-rest#272]
Please may you add the field "usersAssigned" to the "JobOrder" entity in the SDK.
https://github.com/bullhorn/sdk-rest/blob/master/src/main/java/com/bullhornsdk/data/model/entity/core/standard/JobOrder.java

I was asked to raise this issue here by bullhorn support for ticket 03817692.

**Comment by payne911** [comment]
`assignedUsers` is already part of the available properties.

However, as it is, with the SDK, I can only access a Wrapper which contains an empty list and the proper amount of data that should have been in the list. I actually have to use the `getAssociation` method.

If that could get fixed, it'd be amazing.

**Comment by SimonOkeeffe** [comment]
the issue we have with assignedUsers is it only returns users who are currently active/enabled. There might be valid values in the Job field on the CRM, but they don't get returned in the calls due to the state of the user currently

usersAssigned also includes deactivated accounts giving you a more accurate reflection of what Bullhorn displays, which is the use case here

**Comment by johnsully83** [comment]
usersAssigned has been added to SDK version 1.2.54.  Thanks!
